# Generated by Django 4.2.4 on 2023-08-11 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='open_suscription',
            new_name='open_subscription',
        ),
    ]
